### ISSUE TITLE
Why is there no bounds checking on Tensor2.apply()?

### ISSUE THREAD

**Issue by Craigacp** [factorie/factorie#359]
We got burned by this where we'd accidentally transposed the indices (i.e. we were accessing a matrix with (j,i) instead of (i,j)) and all the accesses were returning incorrect values.

It looks like the function does no checking of any kind, not even for negative indices. Is there a reason why it's like this?

**Comment by strubell** [comment]
Not sure, you could try adding a fix and see what happens? :)

@lvilnis might know.

If there is a good reason, my guess would be that it has to do with the hairy tree (actually probably a DAG at best) of inheritance that is the Tensor family.

**Comment by Craigacp** [comment]
I looked in Tensor3 and Tensor4, and it doesn't seem to be there either. I've made a patch which I'll run through the unit tests and see if anything breaks. I'll let you know the results.

**Comment by strubell** [comment]
Great

**Comment by lvilnis** [comment]
The reason there's no bounds checking is because (a long time ago in an
older version of Scala, at least) these methods were very slow and we
deleted a lot of safety checks in an attempt to make them fast. I think we
eventually gave up on making them fast and added the "_"-prefixed methods
to grab the arrays directly and manipulate them in e.g. optimization code,
so I wouldn't mind having these checks inserted back.

**Comment by Craigacp** [comment]
Ok. I'm going to reroute apply, update and += so they use singleIndex to calculate the index into the underlying array, and then put bounds and negative values checking in singleIndex. I'll do this for Tensor2, Tensor3 & Tensor4. It looks like the Dense3LayeredTensorLike4 (etc) override the apply and update methods, but they all seem to have appropriate behaviour when supplied with an odd index (i.e. they throw some kind of exception or assert error).

Do you have a preference on assert vs throwing ArrayIndexOutOfBoundsException? It looks like there are asserts on these indices in a couple of places but my preference is to throw a precise exception.

I'll make a pull request with these fixes once you've got back to me.

**Comment by lvilnis** [comment]
I don't have an extremely strong preference but I (maybe wrongly) have
viewed the idea of typed exceptions as a particularly Java-y mechanism
coming from the (imho terrible) idea of checked exceptions. Since Scala
doesn't have checked exceptions, I think the explicitly typed ones are a
bit heavyweight and I would probably prefer assertions. But I could be
wrong.

**Comment by Craigacp** [comment]
Ok. The Scala collections library throws either ArrayIndexOutOfBoundsException for Arrays or IndexOutOfBoundsException for ArrayBuffer, so my preference would be to follow that. It's possible to catch the exception and deal with it which is easier to deal with than catching generic AssertionError (which might catch other things).

**Comment by lvilnis** [comment]
I don't feel too strongly, but in what situation would it be useful to
handle that exception and recover from it, where we couldn't just prevent
the problem in the first place? I don't think we should be catching that
error at all.

**Comment by lvilnis** [comment]
To be clear, I'm happy to be wrong on this -- your production needs are
probably different than my own.

To me assertions are good for identifying coding errors that should be
fixed, whereas exceptions are good for handling failure situations like not
being able to find a file or losing an internet connection.

The line gets a little blurry when talking about library code like factorie
compared to a shrink-wrap software product, since arguably writing code
against factorie is "using" factorie.

**Comment by Craigacp** [comment]
There are a couple of cases where you could interactively use factorie from a shell (not the scala shell) where it's useful to catch whatever stuff comes back to make sure you don't kill the shell when things go wrong. We wrap shells around quite a few of our projects and having the library barf an assertion error in the middle of some command and wipe out your shell is pretty bad.

Plus people can turn the assertions off in the compiler, and this is the kind of thing that they really shouldn't turn off.

**Comment by lvilnis** [comment]
I disagree, I think this kind of thing introduces overhead and should be
turn-off-able, but the general slowness of Scala means if you care about
the absolute best speed, you should just manipulate the arrays directly.
Either way I've said my piece and will defer to your judgment of your
production needs.
